name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: 8
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: List files in build/libs
        run: ls build/libs

      - name: Prepare artifact
        run: |
          cd build/libs
          export JAR=$(find . -name "liquidbounce-b*.jar")
          echo "Found JAR: $JAR"
          if [ -z "$JAR" ]; then
            echo "JAR file not found"
            exit 1
          fi
          export LB_VERSION=$(echo $JAR | sed -r 's/.\/liquidbounce-([a-zA-Z0-9]+)\.jar/\1/')
          export MINECRAFT_VERSION='1.8.9'
          echo "Version: $LB_VERSION, Minecraft: $MINECRAFT_VERSION"
          mkdir -p zip
          cp $JAR zip/liquidbounce.jar
          cd zip
          zip -r liquidbounce.zip *
          md5sum liquidbounce.zip
          cp liquidbounce.zip ../../liquidbounce.zip

      - name: Upload to GitHub Actions artifacts
        uses: actions/upload-artifact@v4
        with:
          name: liquidbounce-client
          path: build/liquidbounce.zip

      - name: Upload to LiquidBounce API
        run: |
          curl --connect-timeout 30 -m 300 -X POST \
            -F "artifact=@build/liquidbounce.zip" \
            -H "Authorization: ${{ secrets.NIGHTLY_PASS }}" \
            -F "gh_id=${{ github.event.head_commit.id }}" \
            -F "gh_ref=${{ github.ref }}" \
            -F "gh_message=${{ github.event.head_commit.message }}" \
            -F "gh_timestamp=${{ github.event.head_commit.timestamp }}" \
            -F "lb_version=$LB_VERSION" \
            -F "mc_version=1.8.9" \
            -F "jre_version=8" \
            -F "subsystem=forge" \
            https://api.liquidbounce.net/api/v1/version/new
